- name: add backports repo
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://http.debian.net/debian/ {{ ansible_distribution_release }}-backports main"
  when: ansible_distribution == "Debian"

- name: install backports-kernel
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - linux-image-4.5.0-0.bpo.2-amd64

