# install bind9 service 
# ---
- name: install bind9
  apt: pkg=bind9 state=installed

- name: deploy named.conf.local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local
  notify:
    - restart bind9

- name: deploy named.conf.options
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options
  notify:
    - restart bind9

#- name: create named.conf.ffdon
#  template: src=named.conf.ffdon.j2 dest=/etc/bind/named.conf.ffdon
#  notify:
#    - restart bind9

- name: create named.conf.default-zones
  template: src=named.conf.default-zones.j2 dest=/etc/bind/named.conf.default-zones
  notify:
    - restart bind9

- name: create named.conf
  template: src=named.conf.j2 dest=/etc/bind/named.conf
  notify:
    - restart bind9

- name: create own db file for each subdomaene
  template: src=db.ffdon.j2 dest=/etc/bind/db.domaene-{{item}}.ffdon
  notify:
    - restart bind9
  with_items: domaenenliste

